DYNAMIC_SCHEDULE: 'true'
QUEUE: 'send_emails, subscribe'
MAILCHIMP_API_KEY: '904ca50315abfb77a18db720781b14ce-us12'
MAILCHIMP_LIST_ID: 'f75f926f98'

development:
  REDIS_URL: 'redis://localhost:6379'
test:
  REDIS_URL: 'redis://h:1111@pub-redis-12167.us-east-1-3.6.ec2.redislabs.com:12167'
