source 'https://rubygems.org'

ruby '2.2.2'

gem 'rails', '4.2.1'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'rolify'
gem 'responders'
gem 'active_decorator'
gem 'devise'
gem 'ffaker'
gem 'newrelic_rpm'
gem 'simple_form'
gem 'country_select'
gem 'slim-rails'
gem 'momentjs-rails'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'rollbar'
gem 'ransack'
gem 'resque', require: 'resque/server'
gem 'resque-scheduler', require: 'resque/scheduler/server'
gem 'figaro'
gem 'foreman'
gem 'foreman-export-initscript', github: 'webgradus/foreman-export-initscript'
gem 'unicorn'
gem 'validates'
gem 'active_model_serializers'
gem 'virtus'
gem 'groupdate'
gem 'draper'
gem 'globalize', '~> 5.0.0'
gem 'http_accept_language'
gem 'kaminari'
gem 'mail_form'
gem 'redcarpet'
gem 'epic-editor-rails'
gem 'friendly_id'
gem 'roo', '~> 2.1.0'
gem 'gibbon'
gem 'statsample'
gem 'lazy_high_charts'
gem 'chartkick'
gem 'awesome_nested_set'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'bullet'
  gem 'html2slim'
  gem 'meta_request'
  gem 'interactive_editor'
  gem 'letter_opener'
  gem 'letter_opener_web'
end

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'awesome_print', require: 'ap'
  gem 'factory_girl_rails'
  gem 'guard'
  gem 'guard-rubocop'
  gem 'guard-rspec'
  gem 'guard-livereload'
  gem 'rack-livereload'
  gem 'hirb'
  gem 'hirb-unicode'
  gem 'pry-byebug'
  gem 'pry-coolline'
  gem 'pry-rails'
  gem 'quiet_assets'
  gem 'rspec-activemodel-mocks'
  gem 'rspec-rails'
  gem 'poltergeist'
  gem 'phantomjs', require: 'phantomjs/poltergeist'
  gem 'selenium-webdriver'
  gem 'spring-commands-rspec'
  gem 'turnip'
  gem 'timecop'
end

group :test do
  gem 'resque_spec'
  gem 'capybara'
  gem 'webmock'
  gem 'vcr'
end

group :production do
  gem 'rails_12factor'
end
